// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'main-window-ready'
  | 'pref-help'
  | 'pref-status'
  | 'pref-title'
  | 'prefs-title'
  | 'sidebar-add-context'
  | 'sidebar-close'
  | 'sidebar-input-placeholder'
  | 'sidebar-model-name'
  | 'sidebar-multiple-items-selected'
  | 'sidebar-no-item-selected'
  | 'sidebar-placeholder-answer'
  | 'sidebar-placeholder-context'
  | 'sidebar-placeholder-inline-formula'
  | 'sidebar-placeholder-latex-placeholder'
  | 'sidebar-placeholder-markdown-ready'
  | 'sidebar-placeholder-rendering'
  | 'sidebar-placeholder-status'
  | 'sidebar-placeholder-surface'
  | 'sidebar-reasoning-depth'
  | 'sidebar-send'
  | 'sidebar-title'
  | 'sidebar-toggle-tooltip'
  | 'sidebar-untitled-item'
  | 'sidebar-welcome-message'
  | 'startup-begin'
  | 'startup-finish';
