// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'main-window-ready'
  | 'pref-codex-path'
  | 'pref-codex-path-description'
  | 'pref-codex-timeout'
  | 'pref-codex-title'
  | 'pref-help'
  | 'pref-status'
  | 'pref-title'
  | 'prefs-title'
  | 'sidebar-add-context'
  | 'sidebar-close'
  | 'sidebar-codex-empty-response'
  | 'sidebar-codex-error'
  | 'sidebar-codex-starting'
  | 'sidebar-input-placeholder'
  | 'sidebar-loading-conversation'
  | 'sidebar-model-name'
  | 'sidebar-multiple-items-selected'
  | 'sidebar-no-item-selected'
  | 'sidebar-reasoning-depth'
  | 'sidebar-send'
  | 'sidebar-title'
  | 'sidebar-toggle-tooltip'
  | 'sidebar-unavailable-message'
  | 'sidebar-untitled-item'
  | 'sidebar-welcome-message'
  | 'startup-begin'
  | 'startup-finish';
