// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "codex.timeoutMs": number;
      "codex.model": string;
      "codex.reasoningEfforts": string;
      "agent.activeProviderId": string;
      "agent.providerProfiles": string;
      "agent.providerSecrets": string;
      "prompts.custom": string;
      "log.verbose": boolean;
    };
  }
}
